version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    links:
      - "tomcat"
      - "mongodb"
      - "mysql"
    restart: always
    volumes:
      - "./htdocs:/var/www/localhost"
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./logs/nginx:/var/log/nginx"
    depends_on:
      - "tomcat"
      - "php"
  tomcat:
    image: tomcat:8.0-jre8-alpine
    container_name: tomcat
    restart: always
    volumes:
      - "./webapp:/usr/local/tomcat/webapps"
    depends_on:
      - "postgres"
      - "redis"
      - "mongodb"
      - "mysql"
    links:
      - "postgres"
      - "redis"
  postgres:
    image: postgres:9.6.5-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=aemini
      - POSTGRES_PASSWORD=secret
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - "./data/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=fakmakyu
      - MYSQL_USER=aemini
      - MYSQL_PASSWORD=secret
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "./data/mongodb:/data/db"
  php:
    build:
      context: ./docker
      dockerfile: php-fpm/Dockerfile
    container_name: php-fpm
    restart: always
    links:
      - "postgres"
      - "mongodb"
      - "mysql"
    volumes:
      - "./htdocs:/var/www/localhost"
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
