version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    links:
      - "tomcat"
    restart: always
    volumes:
      - "./htdocs:/var/www/localhost"
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./logs/nginx:/var/log/nginx"
    depends_on:
      - "tomcat"
      - "php"
  tomcat:
    image: tomcat:8.0-jre8-alpine
    container_name: tomcat
    restart: always
    volumes:
      - "./webapp:/usr/local/tomcat/webapps"
    depends_on:
      - "postgres"
    links:
      - "postgres"
  postgres:
    image: postgres:9.6.5-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=aemini
      - POSTGRES_PASSWORD=secret
  php:
    build:
      context: ./docker
      dockerfile: php-fpm/Dockerfile
    container_name: php-fpm
    restart: always
    links:
      - "postgres"
    volumes:
      - "./htdocs:/var/www/localhost"
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
